//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_Ledger()
        {
            this.acc_VoucherDetail = new HashSet<acc_VoucherDetail>();
        }
    
        public System.Guid LedgerID { get; set; }
        public string LedgerName { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public int GroupID { get; set; }
        public Nullable<decimal> InitialBalance { get; set; }
        public string BalanceType { get; set; }
        public Nullable<bool> RestrictDelete { get; set; }
        public Nullable<System.Guid> ParentLedgerID { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsSystemDefault { get; set; }
        public Nullable<int> OCode { get; set; }
        public string LedgerCode { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual acc_Group acc_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_VoucherDetail> acc_VoucherDetail { get; set; }
    }
}
