//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Group_Maping
    {
        public int ID { get; set; }
        public int Group_MIS_Id { get; set; }
        public int Group_Id { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.Guid EntryBy { get; set; }
        public int OCode { get; set; }
    
        public virtual acc_Group acc_Group { get; set; }
        public virtual acc_tbl_Group_MIS acc_tbl_Group_MIS { get; set; }
    }
}
