//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_SubsidiaryVoucherDetail
    {
        public int Subsidiary_Voucher_Detail_Id { get; set; }
        public System.Guid VoucherDetailID { get; set; }
        public int Subsidiary_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string OCode { get; set; }
    
        public virtual acc_Subsidiary acc_Subsidiary { get; set; }
        public virtual acc_VoucherDetail acc_VoucherDetail { get; set; }
    }
}
