//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_VoucherDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_VoucherDetail()
        {
            this.acc_SubsidiaryVoucherDetail = new HashSet<acc_SubsidiaryVoucherDetail>();
        }
    
        public System.Guid VoucherDetailID { get; set; }
        public int VoucherID { get; set; }
        public System.Guid LedgerID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> VTypeID { get; set; }
        public Nullable<int> OCode { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual acc_Ledger acc_Ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_SubsidiaryVoucherDetail> acc_SubsidiaryVoucherDetail { get; set; }
        public virtual acc_VoucherEntry acc_VoucherEntry { get; set; }
    }
}
