//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_VoucherEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_VoucherEntry()
        {
            this.acc_VoucherDetail = new HashSet<acc_VoucherDetail>();
        }
    
        public int VoucherID { get; set; }
        public string VoucherName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> VTypeID { get; set; }
        public string VNumber { get; set; }
        public Nullable<bool> RestrictDelete { get; set; }
        public Nullable<int> OCode { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_VoucherDetail> acc_VoucherDetail { get; set; }
        public virtual acc_VoucherType acc_VoucherType { get; set; }
    }
}
