//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Chart_of_Account_Maping
    {
        public int id { get; set; }
        public int MIS_Id { get; set; }
        public System.Guid Ledger_Id { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.Guid EntryBy { get; set; }
        public int OCode { get; set; }
    }
}
