//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_Group()
        {
            this.acc_Group1 = new HashSet<acc_Group>();
            this.acc_Group_Maping = new HashSet<acc_Group_Maping>();
            this.acc_Ledger = new HashSet<acc_Ledger>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public int NatureID { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EditedBy { get; set; }
        public Nullable<bool> RestrictDelete { get; set; }
        public Nullable<bool> IsSystemDefault { get; set; }
        public Nullable<int> OCode { get; set; }
        public Nullable<int> RestaurantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_Group> acc_Group1 { get; set; }
        public virtual acc_Group acc_Group2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_Group_Maping> acc_Group_Maping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_Ledger> acc_Ledger { get; set; }
    }
}
