//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtherExpense
    {
        public int ExpenseId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<decimal> Less { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<decimal> Compliment { get; set; }
        public Nullable<decimal> Damage { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblStoreInformation tblStoreInformation { get; set; }
        public virtual tblShift tblShift { get; set; }
    }
}
