//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPHtoSPProductTransfer
    {
        public int SPSProductId { get; set; }
        public Nullable<int> SellsPointId { get; set; }
        public Nullable<int> ProductionHouseId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public Nullable<bool> isIn { get; set; }
        public Nullable<bool> isOut { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Status { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    
        public virtual tblProductInformation tblProductInformation { get; set; }
        public virtual tblProductionHouseInformation tblProductionHouseInformation { get; set; }
        public virtual tblSellsPoint tblSellsPoint { get; set; }
        public virtual tblShift tblShift { get; set; }
    }
}
