//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTransfer
    {
        public int ProductTransferId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> isIn { get; set; }
        public Nullable<bool> isOut { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    
        public virtual tblProductInformation tblProductInformation { get; set; }
        public virtual tblStoreInformation tblStoreInformation { get; set; }
    }
}
