//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRestaurantUserView
    {
        public string UserId { get; set; }
        public decimal restaurant_id { get; set; }
        public int module_id { get; set; }
        public decimal veiw_id { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblRestaurantUserModule tblRestaurantUserModule { get; set; }
        public virtual tblView tblView { get; set; }
    }
}
