//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuppliersProduct
    {
        public int SupplierProductId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> Mapped { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryUser { get; set; }
        public string UserIP { get; set; }
        public string Status { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblProductInformation tblProductInformation { get; set; }
    }
}
