//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStoreInformation()
        {
            this.tblOtherExpenses = new HashSet<tblOtherExpense>();
            this.tblProductInformations = new HashSet<tblProductInformation>();
            this.tblProductTransfers = new HashSet<tblProductTransfer>();
            this.tblSellsPoints = new HashSet<tblSellsPoint>();
        }
    
        public int store_id { get; set; }
        public string store_name { get; set; }
        public bool is_mainStore { get; set; }
        public Nullable<int> ProductionHouseId { get; set; }
        public Nullable<int> ParentStoreId { get; set; }
        public Nullable<int> SellsPointStoreId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> isProductionHouseStore { get; set; }
        public Nullable<bool> IsSellsPointStore { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOtherExpense> tblOtherExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductInformation> tblProductInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductTransfer> tblProductTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSellsPoint> tblSellsPoints { get; set; }
    }
}
